package com.example.stepsplit.ui.theme

import androidx.compose.ui.graphics.Color

val SeedGreen = Color(0xFF1B5E4F)

val md_theme_light_primary = Color(0xFF1B6D5A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA0F2D7)
val md_theme_light_onPrimaryContainer = Color(0xFF002016)
val md_theme_light_secondary = Color(0xFF4A6358)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCE8DA)
val md_theme_light_onSecondaryContainer = Color(0xFF072016)
val md_theme_light_tertiary = Color(0xFF3D6373)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFFBFDF9)
val md_theme_light_onBackground = Color(0xFF191C1A)
val md_theme_light_surface = Color(0xFFFBFDF9)
val md_theme_light_onSurface = Color(0xFF191C1A)
val md_theme_light_surfaceVariant = Color(0xFFDBE5DE)
val md_theme_light_outline = Color(0xFF6F7975)

val md_theme_dark_primary = Color(0xFF84D6BB)
val md_theme_dark_onPrimary = Color(0xFF00382A)
val md_theme_dark_primaryContainer = Color(0xFF00513E)
val md_theme_dark_onPrimaryContainer = Color(0xFFA0F2D7)
val md_theme_dark_secondary = Color(0xFFB0CCBF)
val md_theme_dark_onSecondary = Color(0xFF1C352B)
val md_theme_dark_secondaryContainer = Color(0xFF334B41)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCE8DA)
val md_theme_dark_tertiary = Color(0xFFA5CCDF)
val md_theme_dark_onTertiary = Color(0xFF063542)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_background = Color(0xFF191C1A)
val md_theme_dark_onBackground = Color(0xFFE1E3DF)
val md_theme_dark_surface = Color(0xFF191C1A)
val md_theme_dark_onSurface = Color(0xFFE1E3DF)
val md_theme_dark_surfaceVariant = Color(0xFF3F4945)
val md_theme_dark_outline = Color(0xFF899490)

val WorkoutSegmentColor = Color(0xFF1B6D5A)
val IncidentalSegmentColor = Color(0xFFA0C9BA)
